%include "colon.inc" 

section .data

colon `\t`, sixth
db "tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab tab", 0

colon " ", fifth
db "lol whitespace >_<", 0

colon "Nazar Klyuhanov", fourth
db "https://www.youtube.com/watch?v=FKg8HpO0HYc", 0

colon "dora", third
db "dura", 0

colon "meow murr", second
db "Arigato Gozaimasu", 0 

colon "gimme chocolate", first
db "https://open.spotify.com/track/17ZOICUf4FYlzOAQajt3rN", 0 
